# Data Pre-Processing

In [118]:
# import relevant libaries 
import numpy as np 
import pandas as pd 

# Data Visualization
import seaborn as sns 
import matplotlib.pyplot as plt

In [119]:
df = pd.read_csv("data/Gender_StatsData.csv")

df = df.loc[df['Indicator Name'].str.contains("female", case=False)]
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
11,Arab World,ARB,"Access to anti-retroviral drugs, female (%)",SH.HIV.ARTC.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.405678,20.97654,24.526016,28.636056,33.627633,37.399015,40.84965,42.814275,NaN,NaN
13,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,22.079350,NaN,NaN,25.635403,NaN,NaN,NaN,NaN
15,Arab World,ARB,"Adjusted net enrollment rate, primary, female ...",SE.PRM.TENR.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,84.118780,83.21839,83.344940,83.189960,83.820280,83.994780,84.25278,NaN,NaN,NaN
18,Arab World,ARB,"Age at first marriage, female",SP.DYN.SMAM.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Arab World,ARB,"Age population, age 0, female, interpolated",SP.POP.AG00.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
df['Indicator Name'].unique()

array(['Access to anti-retroviral drugs, female (%)',
       'Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)',
       'Adjusted net enrollment rate, primary, female (% of primary school age children)',
       'Age at first marriage, female',
       'Age population, age 0, female, interpolated',
       'Age population, age 01, female, interpolated',
       'Age population, age 02, female, interpolated',
       'Age population, age 03, female, interpolated',
       'Age population, age 04, female, interpolated',
       'Age population, age 05, female, interpolated',
       'Cause of death, by communicable diseases, ages 15-34, female (% of relevant age group)',
       'Cause of death, by communicable diseases, ages 35-59, female (% of relevant age group)',
       'Cause of death, by injury, ages 15-34, female  (% of relevant age group)',
       'Cause of death, by injury, ages 35-59, female (% of relevant age group)',
       'Cause of death, by non-communicable diseases, ages 15-34, female (% of relevant age group)',
       'Cause of death, by non-communicable diseases, ages 35-59, female (% of relevant age group)',
       'Children in employment, female (% of female children ages 7-14)',
       'Children out of school, primary, female',
       'Completeness of birth registration, female (%)',
       'Contributing family workers, female (% of female employment) (modeled ILO estimate)',
       'Cost of business start-up procedures, female (% of GNI per capita)',
       "Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)",
       'Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)',
       'Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)',
       'Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative)',
       'Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)',
       'Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)',
       "Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)",
       'Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)',
       'Employers, female (% of female employment) (modeled ILO estimate)',
       'Employment in agriculture, female (% of female employment) (modeled ILO estimate)',
       'Employment in industry, female (% of female employment) (modeled ILO estimate)',
       'Employment in services, female (% of female employment) (modeled ILO estimate)',
       'Employment to population ratio, 15+, female (%) (modeled ILO estimate)',
       'Employment to population ratio, 15+, female (%) (national estimate)',
       'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate)',
       'Employment to population ratio, ages 15-24, female (%) (national estimate)',
       'Expected Years of School, Female',
       'Expected years of schooling, female',
       'Female and male surviving spouses have equal rights to inherit assets (1=yes; 0=no)',
       'Female genital mutilation prevalence (%)',
       'Female genital mutilation prevalence (%): Q1 (lowest)',
       'Female genital mutilation prevalence (%): Q2',
       'Female genital mutilation prevalence (%): Q3',
       'Female genital mutilation prevalence (%): Q4',
       'Female genital mutilation prevalence (%): Q5 (highest)',
       'Female headed households (% of households with a female head)',
       'Female migrants (% of international migrant stock)',
       'Female primary school age children out-of-school (%)',
       'Female professional and technical workers (% of total)',
       'Female pupils below minimum reading proficiency at end of primary (%). Low GAML threshold',
       'Female share of employment in senior and middle management (%)',
       'Female share of graduates from Science, Technology, Engineering and Mathematics (STEM) programmes, tertiary (%)',
       'Female share of graduates in Agriculture programmes, tertiary (%)',
       'Female share of graduates in Education programmes, tertiary (%)',
       'Female share of graduates in Engineering, Manufacturing and Construction programmes, tertiary (%)',
       'Female share of graduates in from Business, Administration and Law programmes, tertiary (%)',
       'Female share of graduates in Health and Welfare programmes, tertiary (%)',
       'Female share of graduates in Humanities and Arts programmes, tertiary (%)',
       'Female share of graduates in Information and Communication Technologies programmes, tertiary (%)',
       'Female share of graduates in other fields than Science, Technology, Engineering and Mathematics programmes, tertiary (%)',
       'Female share of graduates in Science programmes, tertiary (%)',
       'Female share of graduates in Services programmes, tertiary (%)',
       'Female share of graduates in Social Science, Business and Law programmes, tertiary (%)',
       'Female share of graduates in unknown or unspecified fields, tertiary (%)',
       'Financial institution account,female(% age 15+)',
       'Firms with female participation in ownership (% of firms)',
       'Firms with female top manager (% of firms)',
       'Fraction of Children Under 5 Not Stunted, Female',
       'Gross graduation ratio, primary, female (%)',
       'Gross graduation ratio, tertiary, female (%)',
       'Harmonized Test Scores, Female',
       'Human Capital Index (HCI), Female (scale 0-1)',
       'Human Capital Index (HCI), Female, Lower Bound (scale 0-1)',
       'Human Capital Index (HCI), Female, Upper Bound (scale 0-1)',
       'Incidence of HIV, ages 15-24, female (per 1,000 uninfected female population ages 15-24)',
       'Incidence of HIV, ages 15-49, female (per 1,000 uninfected female population ages 15-49)',
       'Informal employment, female (% of total non-agricultural employment)',
       'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, female (%) (national estimate)',
       'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)',
       'Labor force participation rate, female (% of female population ages 15+) (national estimate)',
       'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)',
       'Labor force with advanced education, female (% of female working-age population with advanced education)',
       'Labor force with basic education, female (% of female working-age population with basic education)',
       'Labor force with intermediate education, female (% of female working-age population with intermediate education)',
       'Labor force, female',
       'Labor force, female (% of total labor force)',
       'Law mandates equal remuneration for females and males for work of equal value (1=yes; 0=no)',
       'Learning poverty: Share of Female Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%)',
       'Learning-Adjusted Years of School, Female',
       'Life expectancy at age 60, female (years)',
       'Life expectancy at birth, female (years)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, youth female (% of females ages 15-24)',
       'Lower secondary completion rate, female (% of relevant age group)',
       'Mandatory retirement age, female',
       'Mobile money account, female (% age 15+)',
       'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
       'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
       'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
       'Mortality rate, infant, female (per 1,000 live births)',
       'Mortality rate, under-5, female (per 1,000 live births)',
       'Net intake rate in grade 1, female (% of official school-age population)',
       'Number of female business owners', 'Number of female directors',
       'Number of female sole proprietors',
       'Number of infant deaths, female',
       'Number of under-five deaths, female',
       'Own-account workers, female (% of female employment) (modeled ILO estimate)',
       'Part time employment, female (% of total part time employment)',
       'Percentage of students in lower secondary vocational education who are female (%)',
       'Percentage of students in post-secondary non-tertiary vocational education who are female (%)',
       'Percentage of students in upper secondary vocational education who are female (%)',
       'Persistence to grade 5, female (% of cohort)',
       'Population ages 0-14, female', 'Population ages 15-64, female',
       'Population ages 65 and above, female', 'Population, female',
       'Population, female (% of total)',
       'Prevalence of HIV, female (% ages 15-24)',
       'Prevalence of obesity, female (% of female population ages 18+)',
       'Prevalence of overweight, female (% of female adults)',
       'Prevalence of overweight, weight for height, female (% of children under 5)',
       'Prevalence of severe wasting, weight for height, female (% of children under 5)',
       'Prevalence of stunting, height for age, female (% of children under 5)',
       'Prevalence of underweight, weight for age, female (% of children under 5)',
       'Prevalence of wasting, weight for height, female (% of children under 5)',
       'Primary completion rate, female (% of relevant age group)',
       'Primary education, pupils (% female)',
       'Primary education, teachers (% female)',
       'Probability of Survival to Age 5, Female',
       'Progression to secondary school, female (%)',
       'Proportion of time spent on unpaid domestic and care work, female (% of 24 hour day)',
       'Rate of out-of-school youth of upper secondary school age, female (%)',
       'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)',
       'Ratio of female to male labor force participation rate (%) (national estimate)',
       'Ratio of female to male youth unemployment rate (% ages 15-24) (modeled ILO estimate)',
       'Ratio of female to male youth unemployment rate (%) (national estimate)',
       'Retirement age with full benefits, female',
       'Retirement age with partial benefits, female',
       'Rural population, female (% of total)',
       'Saved any money in the past year, female  (% age 15+)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, female (% net)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, female (% net)',
       'School enrollment, tertiary, female (% gross)',
       'Secondary education, pupils (% female)',
       'Secondary education, teachers (% female)',
       'Secondary education, vocational pupils (% female)',
       'Self-employed, female (% of female employment) (modeled ILO estimate)',
       'Sex ratio at birth (male births per female births)',
       'Share of female business owners (% of total business owners)',
       'Share of female directors (% of total directors)',
       'Share of female sole proprietors  (% of sole proprietors)',
       'Share of female students in lower secondary education enrolled in vocational programmes (%)',
       'Share of female students in post-secondary non-tertiary education enrolled in vocational programmes (%)',
       'Share of female students in upper secondary education enrolled in vocational programmes (%)',
       'Share of youth not in education, employment or training, female (% of female youth population)',
       'Smoking prevalence, females (% of adults)',
       'Start-up procedures to register a business, female (number)',
       'Suicide mortality rate, female (per 100,000 female population)',
       'Survival Rate from Age 15-60, Female',
       'Tertiary education, academic staff (% female)',
       'Time required to start a business, female (days)',
       'Time-related underemployment, female (% of employment)',
       'Total alcohol consumption per capita, female (liters of pure alcohol, projected estimates, female 15+ years of age)',
       'Unemployment with advanced education, female (% of female labor force with advanced education)',
       'Unemployment with basic education, female (% of female labor force with basic education)',
       'Unemployment with intermediate education, female (% of female labor force with intermediate education)',
       'Unemployment, female (% of female labor force) (modeled ILO estimate)',
       'Unemployment, female (% of female labor force) (national estimate)',
       'Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)',
       'Unemployment, youth female (% of female labor force ages 15-24) (national estimate)',
       'Urban population, female (% of total)',
       'Vulnerable employment, female (% of female employment) (modeled ILO estimate)',
       'Wage and salaried workers, female (% of female employment) (modeled ILO estimate)',
       'Youth illiterate population, 15-24 years, % female',
       'Youth illiterate population, 15-24 years, female (number)'],
      dtype=object)

- Access to anti-retroviral drugs, female (%)',
- 'Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)',
- 'Adjusted net enrollment rate, primary, female (% of primary school age children)',
- 'Age at first marriage, female',
- 'Age population, age 0, female, interpolated',
- 'Age population, age 01, female, interpolated',
- 'Age population, age 02, female, interpolated',
- 'Age population, age 03, female, interpolated',
- 'Age population, age 04, female, interpolated',
- 'Age population, age 05, female, interpolated',
- 'Cause of death, by communicable diseases, ages 15-34, female (% of relevant age group)',
- 'Cause of death, by communicable diseases, ages 35-59, female (% of relevant age group)',
- 'Cause of death, by injury, ages 15-34, female  (% of relevant age group)',
- 'Cause of death, by injury, ages 35-59, female (% of relevant age group)',
       'Cause of death, by non-communicable diseases, ages 15-34, female (% of relevant age group)',
       'Cause of death, by non-communicable diseases, ages 35-59, female (% of relevant age group)',
       'Children in employment, female (% of female children ages 7-14)',
       'Children out of school, primary, female',
       'Completeness of birth registration, female (%)',
       'Contributing family workers, female (% of female employment) (modeled ILO estimate)',
       'Cost of business start-up procedures, female (% of GNI per capita)',
       "Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)",
       'Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)',
       'Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)',
       'Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative)',
       'Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)',
       'Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)',
       "Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)",
       'Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)',
       'Employers, female (% of female employment) (modeled ILO estimate)',
       'Employment in agriculture, female (% of female employment) (modeled ILO estimate)',
       'Employment in industry, female (% of female employment) (modeled ILO estimate)',
       'Employment in services, female (% of female employment) (modeled ILO estimate)',
       'Employment to population ratio, 15+, female (%) (modeled ILO estimate)',
       'Employment to population ratio, 15+, female (%) (national estimate)',
       'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate)',
       'Employment to population ratio, ages 15-24, female (%) (national estimate)',
       'Expected Years of School, Female',
       'Expected years of schooling, female',
       'Female and male surviving spouses have equal rights to inherit assets (1=yes; 0=no)',
       'Female genital mutilation prevalence (%)',
       'Female genital mutilation prevalence (%): Q1 (lowest)',
       'Female genital mutilation prevalence (%): Q2',
       'Female genital mutilation prevalence (%): Q3',
       'Female genital mutilation prevalence (%): Q4',
       'Female genital mutilation prevalence (%): Q5 (highest)',
       'Female headed households (% of households with a female head)',
       'Female migrants (% of international migrant stock)',
       'Female primary school age children out-of-school (%)',
       'Female professional and technical workers (% of total)',
       'Female pupils below minimum reading proficiency at end of primary (%). Low GAML threshold',
       'Female share of employment in senior and middle management (%)',
       'Female share of graduates from Science, Technology, Engineering and Mathematics (STEM) programmes, tertiary (%)',
       'Female share of graduates in Agriculture programmes, tertiary (%)',
       'Female share of graduates in Education programmes, tertiary (%)',
       'Female share of graduates in Engineering, Manufacturing and Construction programmes, tertiary (%)',
       'Female share of graduates in from Business, Administration and Law programmes, tertiary (%)',
       'Female share of graduates in Health and Welfare programmes, tertiary (%)',
       'Female share of graduates in Humanities and Arts programmes, tertiary (%)',
       'Female share of graduates in Information and Communication Technologies programmes, tertiary (%)',
       'Female share of graduates in other fields than Science, Technology, Engineering and Mathematics programmes, tertiary (%)',
       'Female share of graduates in Science programmes, tertiary (%)',
       'Female share of graduates in Services programmes, tertiary (%)',
       'Female share of graduates in Social Science, Business and Law programmes, tertiary (%)',
       'Female share of graduates in unknown or unspecified fields, tertiary (%)',
       'Financial institution account,female(% age 15+)',
       'Firms with female participation in ownership (% of firms)',
       'Firms with female top manager (% of firms)',
       'Fraction of Children Under 5 Not Stunted, Female',
       'Gross graduation ratio, primary, female (%)',
       'Gross graduation ratio, tertiary, female (%)',
       'Harmonized Test Scores, Female',
       'Human Capital Index (HCI), Female (scale 0-1)',
       'Human Capital Index (HCI), Female, Lower Bound (scale 0-1)',
       'Human Capital Index (HCI), Female, Upper Bound (scale 0-1)',
       'Incidence of HIV, ages 15-24, female (per 1,000 uninfected female population ages 15-24)',
       'Incidence of HIV, ages 15-49, female (per 1,000 uninfected female population ages 15-49)',
       'Informal employment, female (% of total non-agricultural employment)',
       'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)',
       'Labor force participation rate for ages 15-24, female (%) (national estimate)',
       'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)',
       'Labor force participation rate, female (% of female population ages 15+) (national estimate)',
       'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)',
       'Labor force with advanced education, female (% of female working-age population with advanced education)',
       'Labor force with basic education, female (% of female working-age population with basic education)',
       'Labor force with intermediate education, female (% of female working-age population with intermediate education)',
       'Labor force, female',
       'Labor force, female (% of total labor force)',
       'Law mandates equal remuneration for females and males for work of equal value (1=yes; 0=no)',
       'Learning poverty: Share of Female Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%)',
       'Learning-Adjusted Years of School, Female',
       'Life expectancy at age 60, female (years)',
       'Life expectancy at birth, female (years)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, youth female (% of females ages 15-24)',
       'Lower secondary completion rate, female (% of relevant age group)',
       'Mandatory retirement age, female',
       'Mobile money account, female (% age 15+)',
       'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
       'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
       'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
       'Mortality rate, infant, female (per 1,000 live births)',
       'Mortality rate, under-5, female (per 1,000 live births)',
       'Net intake rate in grade 1, female (% of official school-age population)',
       'Number of female business owners', 'Number of female directors',
       'Number of female sole proprietors',
       'Number of infant deaths, female',
       'Number of under-five deaths, female',
       'Own-account workers, female (% of female employment) (modeled ILO estimate)',
       'Part time employment, female (% of total part time employment)',
       'Percentage of students in lower secondary vocational education who are female (%)',
       'Percentage of students in post-secondary non-tertiary vocational education who are female (%)',
       'Percentage of students in upper secondary vocational education who are female (%)',
       'Persistence to grade 5, female (% of cohort)',
       'Population ages 0-14, female', 'Population ages 15-64, female',
       'Population ages 65 and above, female', 'Population, female',
       'Population, female (% of total)',
       'Prevalence of HIV, female (% ages 15-24)',
       'Prevalence of obesity, female (% of female population ages 18+)',
       'Prevalence of overweight, female (% of female adults)',
       'Prevalence of overweight, weight for height, female (% of children under 5)',
       'Prevalence of severe wasting, weight for height, female (% of children under 5)',
       'Prevalence of stunting, height for age, female (% of children under 5)',
       'Prevalence of underweight, weight for age, female (% of children under 5)',
       'Prevalence of wasting, weight for height, female (% of children under 5)',
       'Primary completion rate, female (% of relevant age group)',
       'Primary education, pupils (% female)',
       'Primary education, teachers (% female)',
       'Probability of Survival to Age 5, Female',
       'Progression to secondary school, female (%)',
       'Proportion of time spent on unpaid domestic and care work, female (% of 24 hour day)',
       'Rate of out-of-school youth of upper secondary school age, female (%)',
       'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)',
       'Ratio of female to male labor force participation rate (%) (national estimate)',
       'Ratio of female to male youth unemployment rate (% ages 15-24) (modeled ILO estimate)',
       'Ratio of female to male youth unemployment rate (%) (national estimate)',
       'Retirement age with full benefits, female',
       'Retirement age with partial benefits, female',
       'Rural population, female (% of total)',
       'Saved any money in the past year, female  (% age 15+)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, female (% net)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, female (% net)',
       'School enrollment, tertiary, female (% gross)',
       'Secondary education, pupils (% female)',
       'Secondary education, teachers (% female)',
       'Secondary education, vocational pupils (% female)',
       'Self-employed, female (% of female employment) (modeled ILO estimate)',
       'Sex ratio at birth (male births per female births)',
       'Share of female business owners (% of total business owners)',
       'Share of female directors (% of total directors)',
       'Share of female sole proprietors  (% of sole proprietors)',
       'Share of female students in lower secondary education enrolled in vocational programmes (%)',
       'Share of female students in post-secondary non-tertiary education enrolled in vocational programmes (%)',
       'Share of female students in upper secondary education enrolled in vocational programmes (%)',
       'Share of youth not in education, employment or training, female (% of female youth population)',
       'Smoking prevalence, females (% of adults)',
       'Start-up procedures to register a business, female (number)',
       'Suicide mortality rate, female (per 100,000 female population)',
       'Survival Rate from Age 15-60, Female',
       'Tertiary education, academic staff (% female)',
       'Time required to start a business, female (days)',
- 'Time-related underemployment, female (% of employment)',
- 'Total alcohol consumption per capita, female (liters of pure alcohol, projected estimates, female 15+ years of age)',
- 'Unemployment with advanced education, female (% of female labor force with advanced education)',
- 'Unemployment with basic education, female (% of female labor force with basic education)',
- 'Unemployment with intermediate education, female (% of female labor force with intermediate education)',
- 'Unemployment, female (% of female labor force) (modeled ILO estimate)',
- 'Unemployment, female (% of female labor force) (national estimate)',
- 'Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)',
- 'Unemployment, youth female (% of female labor force ages 15-24) (national estimate)',
- 'Urban population, female (% of total)',
- 'Vulnerable employment, female (% of female employment) (modeled ILO estimate)',
- 'Wage and salaried workers, female (% of female employment) (modeled ILO estimate)',
- 'Youth illiterate population, 15-24 years, % female',
- 'Youth illiterate population, 15-24 years, female (number)']

## STEM

In [84]:
df = df[df['Indicator Code']=='UIS.FGP.5T8.F600']
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
138,Arab World,ARB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
762,Caribbean small states,CSS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,Central Europe and the Baltics,CEB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,Early-demographic dividend,EAR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2634,East Asia & Pacific,EAS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
df.isna().any().sum()

62

In [86]:
# df.isna().sum()

In [87]:
# df.reset_index(inplace = True)

In [88]:
df.shape

(263, 66)

In [89]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', 'Unnamed: 65'],
      dtype='object')

In [90]:
# df.dropna(thresh=60*0.7, axis='rows', inplace = True)

In [91]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
138,Arab World,ARB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
762,Caribbean small states,CSS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,Central Europe and the Baltics,CEB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,Early-demographic dividend,EAR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2634,East Asia & Pacific,EAS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
# df['Unnamed: 65'].isna().sum()

In [93]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', 'Unnamed: 65'],
      dtype='object')

In [58]:
df.isna().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              263
1961              263
1962              263
1963              263
1964              263
1965              263
1966              263
1967              263
1968              263
1969              263
1970              263
1971              263
1972              263
1973              263
1974              263
1975              263
1976              263
1977              263
1978              263
1979              263
1980              263
1981              263
1982              263
1983              263
1984              263
1985              263
                 ...
1991              263
1992              263
1993              263
1994              263
1995              263
1996              263
1997              263
1998              257
1999              229
2000              221
2001              221
2002              218
2003              217
2004              214
2005              216
2006              220
2007              207
2008              205
2009              205
2010              203
2011              201
2012              202
2013              226
2014              212
2015              172
2016              172
2017              182
2018              219
2019              261
2020              263
Length: 65, dtype: int64

In [94]:
cols = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
        '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018']

In [95]:
df = df[cols]

In [96]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1999,2000,2001,2002,2003,2004,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
138,Arab World,ARB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
762,Caribbean small states,CSS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,Central Europe and the Baltics,CEB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,Early-demographic dividend,EAR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2634,East Asia & Pacific,EAS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
df.isna().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1999              229
2000              221
2001              221
2002              218
2003              217
2004              214
2005              216
2006              220
2007              207
2008              205
2009              205
2010              203
2011              201
2012              202
2013              226
2014              212
2015              172
2016              172
2017              182
2018              219
dtype: int64

In [98]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1999,2000,2001,2002,2003,2004,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
138,Arab World,ARB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
762,Caribbean small states,CSS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,Central Europe and the Baltics,CEB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,Early-demographic dividend,EAR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2634,East Asia & Pacific,EAS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
df = df.dropna(thresh=19*0.7, axis = 'rows')

In [108]:
df

,Country Name,Country Code,Indicator Name,Indicator Code,1999,2000,2001,2002,2003,2004,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
31338,Andorra,AND,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,30.00000,23.52941,11.76471,...,NaN,NaN,NaN,33.33333,NaN,NaN,NaN,100.00000,100.00000,0.00000
35082,Australia,AUS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,26.00037,26.10591,NaN,...,18.75755,NaN,19.10183,NaN,19.35603,19.07006,19.14908,NaN,21.75496,NaN
40074,Belgium,BEL,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,12.00215,14.21882,11.48240,NaN,NaN,...,5.64558,8.74867,8.02810,8.05897,6.79766,7.34463,7.81123,5.63075,9.87884,NaN
41946,Bermuda,BMU,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,33.33333,NaN,NaN,NaN,...,45.45455,33.33333,40.00000,66.66667,NaN,NaN,28.57143,NaN,9.09091,33.33333
45066,Brazil,BRA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,32.10390,28.74314,26.68425,24.18797,...,18.39748,18.25965,16.97174,17.33484,NaN,15.29114,15.01138,14.62630,14.55104,NaN
46314,Brunei Darussalam,BRN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,62.96296,71.05263,65.62500,NaN,72.72727,44.44444,...,58.06452,53.62319,87.50000,54.25532,NaN,NaN,44.01806,45.79208,NaN,41.86047
46938,Bulgaria,BGR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,61.33005,69.51788,60.03236,46.89507,51.21951,51.91313,...,45.00434,40.66952,39.72780,39.04110,41.35021,37.90738,39.03935,40.04616,38.74001,NaN
53802,Chile,CHL,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,26.48016,...,16.04723,14.24652,NaN,11.55349,42.91498,11.66367,12.54434,12.94400,12.74434,NaN
58794,Croatia,HRV,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,32.87197,NaN,28.06452,23.97094,20.04405,NaN,...,15.81876,16.73152,NaN,15.44554,NaN,19.86063,18.33674,21.25935,21.00213,NaN
60666,Cyprus,CYP,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,44.73684,NaN,NaN,44.11765,28.27586,29.51542,...,30.84112,37.14286,20.18072,23.63636,30.52209,35.89744,35.41667,30.65327,28.45850,NaN
61290,Czech Republic,CZE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.62656,11.86703,12.88591,12.88303,20.65761,21.26568,...,15.06069,13.68960,13.62658,14.20442,14.27967,16.23874,13.48753,15.26864,15.56509,NaN
61914,Denmark,DNK,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,16.37081,14.55026,14.18862,18.83273,19.49008,23.72029,...,19.82379,19.49861,23.41320,24.37428,21.71168,23.01948,19.74738,21.29366,24.00102,NaN
65658,El Salvador,SLV,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,43.57459,44.97154,NaN,...,36.01763,37.34644,34.88806,34.06773,NaN,NaN,30.48780,27.96646,25.98253,26.15804
67530,Estonia,EST,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.41441,22.15569,32.53589,21.75926,24.70588,28.20513,...,24.55446,25.89928,25.60976,20.35398,23.77622,27.73585,29.84496,26.99387,28.89201,NaN
70650,Finland,FIN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,35.08260,40.38610,39.54023,42.35294,40.84589,42.91915,...,26.97368,28.39952,27.45334,23.85148,23.68920,26.39448,19.31818,20.64174,20.74618,NaN
71274,France,FRA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,17.48784,NaN,20.74563,21.68467,17.18799,...,14.62936,NaN,NaN,16.13641,17.93629,16.69439,16.72171,16.45824,NaN,NaN
73770,Georgia,GEO,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,75.67568,48.83721,55.55556,55.55556,14.28571,41.66667,...,NaN,43.74343,NaN,37.04520,NaN,NaN,NaN,26.84211,24.50408,23.64706
76266,Greece,GRC,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,32.16595,...,NaN,39.95179,37.85851,37.20862,36.00741,35.37415,NaN,38.76074,35.68569,NaN
83130,Hungary,HUN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.31127,15.63055,21.10940,18.72832,22.35940,28.22523,...,19.31572,18.01920,15.37028,16.79467,17.08333,17.76375,23.33333,18.81793,16.70346,NaN
83754,Iceland,ISL,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,21.25000,29.13386,23.07692,23.72881,28.08219,27.81065,...,20.00000,20.51282,NaN,12.96296,NaN,NaN,NaN,NaN,NaN,NaN
86874,Ireland,IRL,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,44.70254,45.71893,40.33831,37.73276,36.78565,32.63274,...,24.72826,22.26436,NaN,40.53751,19.93968,19.57627,20.27555,20.85069,NaN,NaN
88746,Italy,ITA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.87793,27.12177,22.51481,20.76923,21.22291,23.26022,...,NaN,NaN,23.46772,25.45636,16.66667,16.26418,19.59654,16.12051,NaN,NaN
93738,"Korea, Rep.",KOR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,48.72796,45.71382,36.33917,38.87096,46.88991,38.04400,...,23.29860,NaN,23.33647,25.28451,25.02166,25.99239,27.33808,28.62947,24.32193,NaN
95610,Kyrgyz Republic,KGZ,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,40.00000,NaN,42.85714,41.61491,43.26599,45.29058,...,42.25268,43.88767,51.05210,46.47971,NaN,NaN,43.25681,43.21346,44.95982,47.42567
96858,Latvia,LVA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,28.61190,35.53114,43.17343,34.90854,31.32372,24.96970,...,21.11399,19.53428,21.24105,21.04623,23.20513,22.27074,20.61170,23.68421,22.68326,NaN
97482,Lebanon,LBN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,34.00810,45.03205,41.36253,NaN,38.93617,...,29.58643,23.63112,30.65903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100602,Lithuania,LTU,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,37.55656,34.59384,36.61017,35.10467,33.37580,26.94356,...,17.17172,17.27973,17.35379,17.26415,15.87678,16.18911,13.79898,11.64725,16.84211,NaN
101850,"Macao SAR, China",MAC,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,17.02128,16.11374,14.52991,14.87179,NaN,NaN,11.96172,16.26794,19.12351,22.74368
102474,Madagascar,MDG,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,26.80653,25.80645,NaN,NaN,NaN,29.37189,29.86887,23.41932,27.82755,33.63636
103722,Malaysia,MYS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,50.50614,...,48.56461,46.65087,47.01448,52.59692,NaN,NaN,44.55067,NaN,NaN,45.99805
105594,Malta,MLT,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,16.66667,0.00000,10.00000,12.82051,14.28571,...,23.27044,19.87952,25.34722,NaN,13.99417,17.86667,18.20896,16.44444,15.97796,NaN
108090,Mexico,MEX,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,43.16758,42.96101,42.84786,42.42819,NaN,...,36.86807,41.96137,40.19761,39.22306,39.29053,37.43118,35.45763,32.17901,28.43665,NaN
110586,Mongolia,MNG,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,33.08271,33.33333,58.33333,39.37824,48.14815,44.60641,...,40.51222,39.97785,34.79888,NaN,NaN,NaN,NaN,NaN,30.94233,37.68421
115578,Netherlands,NLD,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,11.96736,13.37920,13.75516,13.13070,NaN,8.93700,...,NaN,10.92259,NaN,NaN,15.40704,16.57212,NaN,NaN,14.47267,NaN
119322,North Macedonia,MKD,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,49.67320,60.46512,39.66942,61.76471,67.39130,49.18033,...,35.46180,29.52159,35.06201,32.60606,27.91293,27.66532,34.28571,NaN,35.08523,NaN
120570,Norway,NOR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,19.94885,25.16205,24.30300,26.37486,NaN,18.82602,...,21.61017,19.68728,NaN,14.24474,16.85063,15.39877,16.35762,15.96958,15.16080,NaN
123066,Panama,PAN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,57.50000,30.79470,53.85604,...,51.98413,49.61686,49.95730,NaN,NaN,46.89655,55.97190,43.90582,NaN,NaN
126810,Portugal,PRT,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,31.43508,NaN,35.11294,34.64323,24.86938,...,16.08789,23.67688,22.40664,22.35123,24.70149,25.00000,20.99768,23.45391,17.44422,NaN
128058,Qatar,QAT,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,76.78571,64.70588,58.75000,NaN,...,50.68493,49.36709,41.42857,38.75000,NaN,NaN,NaN,46.58120,37.62058,53.38078
132426,Saudi Arabia,SAU,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,13.27095,...,50.18246,63.51129,56.38945,32.13620,NaN,NaN,40.22045,43.61184,46.29440,46.01715
133674,Serbia,SRB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,NaN,NaN,NaN,NaN,NaN,...,36.87287,31.82927,28.64302,26.43189,NaN,NaN,28.05267,27.10608,25.75540,28.55473
136794,Slovak Republic,SVK,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.10917,12.08134,12.09603,12.59542,13.92515,15.81325,...,10.52146,11.71875,11.99654,12.85856,12.43154,15.33711,12.38584,NaN,12.18214,NaN
137418,Slovenia,SVN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,8.06452,NaN,10.66667,8.33333,11.94969,5.98802,...,7.90191,10.15119,7.79661,13.28125,11.95191,14.48809,16.84699,NaN,14.08451,NaN
140538,Spain,ESP,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.59868,24.27219,24.10959,24.36682,23.53905,22.83923,...,17.37595,16.76599,17.40689,15.60358,15.20310,14.72218,14.46526,14.02435,12.97447,NaN
145530,Sweden,SWE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,34.26160,44.74560,40.71534,41.90519,40.16288,35.28148,...,21.92982,18.80492,20.20563,26.06405,25.64412,NaN,27.84627,28.17433,30.23847,NaN
146154,Switzerland,CHE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,NaN,8.24689,10.04098,11.18710,8.86076,9.93166,NaN
152394,Turkey,TUR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.29260,28.71820,28.04650,30.12178,31.48220,35.96116,...,33.09694,33.15971,33.02768,33.44319,NaN,34.46043,NaN,NaN,NaN,NaN
156762,United Kingdom,GBR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,24.60701,25.44204,25.75240,25.30157,24.56532,...,19.39414,18.66546,18.74867,18.79531,19.24576,18.80898,19.27337,19.38466,NaN,NaN
161754,West Bank and Gaza,PSE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,47.55556,52.28519,52.67974,NaN,46.79089,53.71179,...,43.39414,46.62857,45.95032,48.27586,NaN,NaN,49.19691,49.95206,48.29083,45.60738

In [109]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018'],
      dtype='object')

In [110]:
df.isna().sum()

Country Name       0
Country Code       0
Indicator Name     0
Indicator Code     0
1999               8
2000               0
2001              16
2002               2
2003               0
2004               2
2005               2
2006               2
2007               0
2008               2
2009               0
2010               0
2011               0
2012               2
2013               8
2014               8
2015               0
2016               0
2017               0
2018               0
dtype: int64

In [111]:
df.shape

(215, 24)

In [112]:
df = df.fillna(method = 'ffill', axis = 0)

In [113]:
df

,Country Name,Country Code,Indicator Name,Indicator Code,1999,2000,2001,2002,2003,2004,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
30090,Algeria,DZA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,NaN,67.85714,NaN,...,47.20217,48.80532,47.97473,NaN,NaN,NaN,51.76786,54.27659,46.48218,48.93372
30714,American Samoa,ASM,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,NaN,67.85714,NaN,...,47.20217,48.80532,47.97473,NaN,NaN,NaN,51.76786,54.27659,46.48218,48.93372
31338,Andorra,AND,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,30.00000,23.52941,11.76471,...,47.20217,48.80532,47.97473,33.33333,NaN,NaN,51.76786,100.00000,100.00000,0.00000
31962,Angola,AGO,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,100.00000,23.52941,11.76471,...,47.20217,48.80532,47.97473,33.33333,NaN,NaN,37.95987,100.00000,100.00000,0.00000
32586,Antigua and Barbuda,ATG,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,100.00000,23.52941,11.76471,...,34.21053,70.58824,73.33333,33.33333,NaN,NaN,37.95987,100.00000,100.00000,0.00000
33210,Argentina,ARG,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,100.00000,23.52941,11.76471,...,37.01054,33.04348,73.33333,33.33333,NaN,NaN,37.95987,100.00000,100.00000,0.00000
33834,Armenia,ARM,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,100.00000,23.52941,11.76471,...,37.01054,35.86066,73.33333,33.33333,NaN,NaN,25.14045,28.97436,30.58824,38.47167
34458,Aruba,ABW,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,NaN,45.45455,NaN,100.00000,23.52941,11.76471,...,37.01054,35.86066,73.33333,33.33333,NaN,NaN,25.14045,28.97436,30.58824,38.47167
35082,Australia,AUS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,26.00037,26.10591,11.76471,...,18.75755,35.86066,19.10183,33.33333,19.35603,19.07006,19.14908,28.97436,21.75496,38.47167
35706,Austria,AUT,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,26.00037,26.10591,11.76471,...,18.75755,35.86066,19.10183,33.33333,13.15350,14.06318,13.65430,14.29883,21.75496,38.47167
36330,Azerbaijan,AZE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,26.00037,26.10591,11.76471,...,36.41536,38.35616,37.66667,36.81592,13.15350,14.06318,35.34816,41.11718,46.81107,45.96774
36954,"Bahamas, The",BHS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,26.00037,26.10591,11.76471,...,36.41536,38.35616,37.66667,36.81592,13.15350,14.06318,35.34816,41.11718,46.81107,45.96774
37578,Bahrain,BHR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,26.00037,69.29134,11.76471,...,36.41536,38.35616,37.66667,36.81592,13.15350,14.06318,48.88889,50.68120,47.76119,47.13805
38202,Bangladesh,BGD,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,13.57285,15.05065,11.76471,...,36.41536,38.35616,37.66667,36.81592,13.15350,14.06318,48.88889,27.76188,27.76188,27.25023
38826,Barbados,BRB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,13.57285,15.05065,11.76471,...,36.41536,38.35616,40.54054,36.81592,13.15350,14.06318,48.88889,27.76188,27.76188,27.25023
39450,Belarus,BLR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,25.42334,NaN,13.57285,15.05065,11.76471,...,36.41536,38.35616,40.54054,36.81592,13.15350,14.06318,24.20359,22.20681,23.92789,23.03968
40074,Belgium,BEL,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,14.21882,11.48240,15.05065,11.76471,...,5.64558,8.74867,8.02810,8.05897,6.79766,7.34463,7.81123,5.63075,9.87884,23.03968
40698,Belize,BLZ,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,14.21882,11.48240,15.05065,11.76471,...,5.64558,8.74867,8.02810,8.05897,6.79766,7.34463,19.44444,5.63075,9.87884,23.03968
41322,Benin,BEN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,14.21882,11.48240,15.05065,11.76471,...,5.64558,8.74867,22.79202,8.05897,6.79766,18.51852,55.06884,5.63075,9.87884,23.03968
41946,Bermuda,BMU,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,33.33333,11.48240,15.05065,11.76471,...,45.45455,33.33333,40.00000,66.66667,6.79766,18.51852,28.57143,5.63075,9.09091,33.33333
42570,Bhutan,BTN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,33.33333,11.48240,15.05065,11.76471,...,45.45455,33.33333,40.00000,66.66667,6.79766,18.51852,28.57143,5.63075,9.09091,33.33333
43194,Bolivia,BOL,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,33.33333,11.48240,15.05065,11.76471,...,45.45455,33.33333,40.00000,66.66667,6.79766,18.51852,28.57143,5.63075,9.09091,33.33333
43818,Bosnia and Herzegovina,BIH,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,33.33333,11.48240,15.05065,11.76471,...,45.45455,33.33333,40.00000,66.66667,6.79766,18.51852,27.68000,18.05556,27.04225,28.17824
44442,Botswana,BWA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,33.33333,11.48240,15.05065,11.76471,...,45.45455,33.33333,40.00000,66.66667,6.79766,18.51852,27.68000,18.05556,27.04225,28.17824
45066,Brazil,BRA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,32.10390,28.74314,26.68425,24.18797,...,18.39748,18.25965,16.97174,17.33484,6.79766,15.29114,15.01138,14.62630,14.55104,28.17824
45690,British Virgin Islands,VGB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.40197,12.00215,32.10390,28.74314,26.68425,24.18797,...,63.63636,18.25965,16.97174,17.33484,6.79766,15.29114,15.01138,14.62630,14.55104,28.17824
46314,Brunei Darussalam,BRN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,62.96296,71.05263,65.62500,28.74314,72.72727,44.44444,...,58.06452,53.62319,87.50000,54.25532,6.79766,15.29114,44.01806,45.79208,14.55104,41.86047
46938,Bulgaria,BGR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,61.33005,69.51788,60.03236,46.89507,51.21951,51.91313,...,45.00434,40.66952,39.72780,39.04110,41.35021,37.90738,39.03935,40.04616,38.74001,41.86047
47562,Burkina Faso,BFA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,61.33005,69.51788,60.03236,46.89507,51.21951,51.91313,...,45.00434,40.66952,9.65251,9.65909,41.35021,0.00000,29.54545,28.57143,38.74001,41.86047
48186,Burundi,BDI,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,61.33005,69.51788,60.03236,46.89507,51.21951,51.91313,...,45.00434,28.36879,9.65251,9.65909,41.35021,0.00000,29.54545,29.08068,26.55311,41.86047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145530,Sweden,SWE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,34.26160,44.74560,40.71534,41.90519,40.16288,35.28148,...,21.92982,18.80492,20.20563,26.06405,25.64412,14.72218,27.84627,28.17433,30.23847,37.64299
146154,Switzerland,CHE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,11.18710,8.86076,9.93166,37.64299
146778,Syrian Arab Republic,SYR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,11.18710,57.31293,9.93166,37.64299
147402,Tajikistan,TJK,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,11.18710,57.31293,9.93166,37.64299
148026,Tanzania,TZA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,11.18710,57.31293,9.93166,37.64299
148650,Thailand,THA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,50.55515,47.85432,9.93166,37.64299
149274,Timor-Leste,TLS,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,50.55515,47.85432,9.93166,37.64299
149898,Togo,TGO,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,50.55515,47.85432,9.93166,37.64299
150522,Tonga,TON,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,50.55515,47.85432,9.93166,37.64299
151146,Trinidad and Tobago,TTO,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,26.06405,8.24689,10.04098,50.55515,47.85432,9.93166,37.64299
151770,Tunisia,TUN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,14.17937,16.60527,13.80229,14.16208,11.42857,11.58168,...,12.75000,12.33739,9.35738,46.50835,8.24689,10.04098,54.09677,55.46661,9.93166,55.64061
152394,Turkey,TUR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.29260,28.71820,28.04650,30.12178,31.48220,35.96116,...,33.09694,33.15971,33.02768,33.44319,8.24689,34.46043,54.09677,55.46661,9.93166,55.64061
153018,Turkmenistan,TKM,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.29260,28.71820,28.04650,30.12178,31.48220,35.96116,...,33.09694,33.15971,33.02768,33.44319,8.24689,34.46043,54.09677,55.46661,9.93166,55.64061
153642,Turks and Caicos Islands,TCA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.29260,28.71820,28.04650,30.12178,31.48220,35.96116,...,33.09694,33.15971,33.02768,33.44319,8.24689,34.46043,54.09677,55.46661,9.93166,55.64061
154266,Tuvalu,TUV,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,26.29260,28.71820,28.04650,30.12178,31.48220,35.96116,...,33.09694,33.15971,33.02768,33.44319,8.24689,34.46043,54.09677,55.46661,9.93166,55.64061
154890,Uganda,UGA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,16.66667,16.66667,28.04650,30.12178,31.48220,30.09709,...,33.09694,33.15971,33.02768,33.44319,8.24689,34.46043,54.09677,55.46661,9.93166,55.64061
155514,Ukraine,UKR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,16.66667,16.66667,28.04650,30.12178,31.48220,30.09709,...,33.09694,33.15971,33.02768,24.13819,8.24689,34.46043,20.77291,19.96523,19.31067,17.46342
156138,United Arab Emirates,ARE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,16.66667,16.66667,28.04650,30.12178,31.48220,30.09709,...,33.09694,33.15971,53.64742,61.14263,8.24689,34.46043,50.55762,57.78230,55.39084,17.46342
156762,United Kingdom,GBR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,24.60701,25.44204,25.75240,25.30157,24.56532,...,19.39414,18.66546,18.74867,18.79531,19.24576,18.80898,19.27337,19.38466,55.39084,17.46342
157386,United States,USA,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,24.60701,25.44204,25.75240,25.30157,24.56532,...,19.39414,22.10311,21.63908,21.26469,20.93191,21.00502,22.86417,23.60926,55.39084,17.46342
158010,Uruguay,URY,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,24.60701,25.44204,25.75240,25.30157,24.56532,...,25.76923,23.20000,21.63908,21.26469,20.93191,21.00502,22.86417,23.60926,17.65799,17.46342
158634,Uzbekistan,UZB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,24.60701,25.44204,25.75240,25.30157,24.56532,...,25.76923,23.20000,21.63908,21.26469,20.93191,21.00502,22.86417,23.60926,17.65799,17.83377
159258,Vanuatu,VUT,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,24.60701,25.44204,25.75240,25.30157,24.56532,...,25.76923,23.20000,21.63908,21.26469,20.93191,21.00502,22.86417,23.60926,17.65799,17.83377
159882,"Venezuela, RB",VEN,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,53.54308,25.44204,25.75240,25.30157,24.56532,...,25.76923,23.20000,21.63908,21.26469,20.93191,21.00502,22.86417,23.60926,17.65799,17.83377
160506,Vietnam,VNM,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,53.54308,25.44204,25.75240,25.30157,24.56532,...,25.76923,23.20000,21.63908,21.26469,20.93191,21.00502,48.22154,26.43116,17.65799,17.83377
161130,Virgin Islands (U.S.),VIR,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,27.28140,53.54308,25.44204,25.75240,25.30157,24.56532,...,25.76923,23.20000,21.63908,21.26469,20.93191,21.00502,48.22154,26.43116,17.65799,17.83377
161754,West Bank and Gaza,PSE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,47.55556,52.28519,52.67974,25.75240,46.79089,53.71179,...,43.39414,46.62857,45.95032,48.27586,20.93191,21.00502,49.19691,49.95206,48.29083,45.60738
162378,"Yemen, Rep.",YEM,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,47.55556,52.28519,52.67974,25.75240,46.79089,53.71179,...,43.39414,46.62857,45.95032,48.27586,20.93191,21.00502,49.19691,49.95206,48.29083,45.60738
163002,Zambia,ZMB,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,47.55556,52.28519,52.67974,25.75240,46.79089,53.71179,...,43.39414,46.62857,45.95032,48.27586,20.93191,21.00502,49.19691,49.95206,48.29083,45.60738
163626,Zimbabwe,ZWE,Female share of graduates in Information and C...,UIS.FGP.5T8.F600,47.55556,52.28519,52.67974,25.75240,46.79089,53.71179,...,43.39414,47.12154,33.35890,31.92593,20.93191,21.00502,46.11547,49.95206,48.29083,45.60738

In [114]:
df.isna().sum()

Country Name       0
Country Code       0
Indicator Name     0
Indicator Code     0
1999               8
2000               0
2001              16
2002               2
2003               0
2004               2
2005               2
2006               2
2007               0
2008               2
2009               0
2010               0
2011               0
2012               2
2013               8
2014               8
2015               0
2016               0
2017               0
2018               0
dtype: int64

In [115]:
df.to_csv('data/stem_female.csv')

## Migrant